### ISSUE TITLE
[regression] compilation failure

### ISSUE THREAD

**Issue by uartie** [Intel-Media-SDK/MediaSDK#1835] opened 2019-12-12 18:23 UTC
Compilation fails on Ubuntu Xenial with GNU GCC 5.4.0 since pull-request #1793 was merged (commit 919ea65ecb05fec07363abee91e355ec7ed4a01f)

```
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator< <template-parameter-1-1> >::construct(_Up*, _Args&& ...) [with _Up = std::pair<const unsigned int, std::unique_ptr<unsigned char []> >; _Args = {unsigned int&, unsigned char*&}; _Tp = std::_Rb_tree_node<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >]':
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from 'static void std::allocator_traits<std::allocator<_Tp> >::construct(std::allocator_traits<std::allocator<_Tp> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const unsigned int, std::unique_ptr<unsigned char []> >; _Args = {unsigned int&, unsigned char*&}; _Tp = std::_Rb_tree_node<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; std::allocator_traits<std::allocator<_Tp> >::allocator_type = std::allocator<std::_Rb_tree_node<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > > >]'
/usr/include/c++/5/bits/stl_tree.h:529:32:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_construct_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type, _Args&& ...) [with _Args = {unsigned int&, unsigned char*&}; _Key = unsigned int; _Val = std::pair<const unsigned int, std::unique_ptr<unsigned char []> >; _KeyOfValue = std::_Select1st<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; _Compare = std::less<unsigned int>; _Alloc = std::allocator<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >*]'
/usr/include/c++/5/bits/stl_tree.h:546:21:   required from 'std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {unsigned int&, unsigned char*&}; _Key = unsigned int; _Val = std::pair<const unsigned int, std::unique_ptr<unsigned char []> >; _KeyOfValue = std::_Select1st<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; _Compare = std::less<unsigned int>; _Alloc = std::allocator<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >*]'
/usr/include/c++/5/bits/stl_tree.h:2123:33:   required from 'std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_unique(_Args&& ...) [with _Args = {unsigned int&, unsigned char*&}; _Key = unsigned int; _Val = std::pair<const unsigned int, std::unique_ptr<unsigned char []> >; _KeyOfValue = std::_Select1st<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; _Compare = std::less<unsigned int>; _Alloc = std::allocator<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >]'
/usr/include/c++/5/bits/stl_map.h:559:64:   required from 'std::pair<typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<std::pair<const _Key, _Tp> >::other>::iterator, bool> std::map<_Key, _Tp, _Compare, _Alloc>::emplace(_Args&& ...) [with _Args = {unsigned int&, unsigned char*&}; _Key = unsigned int; _Tp = std::unique_ptr<unsigned char []>; _Compare = std::less<unsigned int>; _Alloc = std::allocator<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >; typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<std::pair<const _Key, _Tp> >::other>::iterator = std::_Rb_tree_iterator<std::pair<const unsigned int, std::unique_ptr<unsigned char []> > >]'
/opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/agnostic/hevcehw_extbuf.h:119:42:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to 'std::pair<const unsigned int, std::unique_ptr<unsigned char []> >::pair(unsigned int&, unsigned char*&)'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:206:9: note: candidate: template<class ... _Args1, long unsigned int ..._Indexes1, class ... _Args2, long unsigned int ..._Indexes2> std::pair<_T1, _T2>::pair(std::tuple<_Args1 ...>&, std::tuple<_Args2 ...>&, std::_Index_tuple<_Indexes1 ...>, std::_Index_tuple<_Indexes2 ...>)
         pair(tuple<_Args1...>&, tuple<_Args2...>&,
         ^
/usr/include/c++/5/bits/stl_pair.h:206:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h:120:4: note:   mismatched types 'std::tuple<_Elements ...>' and 'unsigned int'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:155:9: note: candidate: template<class ... _Args1, class ... _Args2> std::pair<_T1, _T2>::pair(std::piecewise_construct_t, std::tuple<_Args1 ...>, std::tuple<_Args2 ...>)
         pair(piecewise_construct_t, tuple<_Args1...>, tuple<_Args2...>);
         ^
/usr/include/c++/5/bits/stl_pair.h:155:9: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h:120:4: note:   cannot convert 'std::forward<unsigned int&>((* & __args#0))' (type 'unsigned int') to type 'std::piecewise_construct_t'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:150:12: note: candidate: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(std::pair<_U1, _U2>&&)
  constexpr pair(pair<_U1, _U2>&& __p)
            ^
/usr/include/c++/5/bits/stl_pair.h:150:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h:120:4: note:   mismatched types 'std::pair<_T1, _T2>' and 'unsigned int'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:144:12: note: candidate: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&)
  constexpr pair(_U1&& __x, _U2&& __y)
            ^
/usr/include/c++/5/bits/stl_pair.h:144:12: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/stl_pair.h:141:38: error: no type named 'type' in 'struct std::enable_if<false, void>'
       template<class _U1, class _U2, class = typename
                                      ^
/usr/include/c++/5/bits/stl_pair.h:138:12: note: candidate: template<class _U2, class> constexpr std::pair<_T1, _T2>::pair(const _T1&, _U2&&)
  constexpr pair(const _T1& __x, _U2&& __y)
            ^
/usr/include/c++/5/bits/stl_pair.h:138:12: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/stl_pair.h:136:27: error: no type named 'type' in 'struct std::enable_if<false, void>'
       template<class _U2, class = typename
                           ^
/usr/include/c++/5/bits/stl_pair.h:133:12: note: candidate: template<class _U1, class> constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&)
  constexpr pair(_U1&& __x, const _T2& __y)
            ^
/usr/include/c++/5/bits/stl_pair.h:133:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h:120:4: note:   cannot convert 'std::forward<unsigned char*&>((* & __args#1))' (type 'unsigned char*') to type 'const std::unique_ptr<unsigned char []>&'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:128:17: note: candidate: constexpr std::pair<_T1, _T2>::pair(std::pair<_T1, _T2>&&) [with _T1 = const unsigned int; _T2 = std::unique_ptr<unsigned char []>]
       constexpr pair(pair&&) = default;
                 ^
/usr/include/c++/5/bits/stl_pair.h:128:17: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/5/bits/stl_pair.h:124:12: note: candidate: template<class _U1, class _U2, class> constexpr std::pair<_T1, _T2>::pair(const std::pair<_U1, _U2>&)
  constexpr pair(const pair<_U1, _U2>& __p)
            ^
/usr/include/c++/5/bits/stl_pair.h:124:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/random:40,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/ext/new_allocator.h:120:4: note:   mismatched types 'const std::pair<_T1, _T2>' and 'unsigned int'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/include/c++/5/utility:70:0,
                 from /usr/include/c++/5/algorithm:60,
                 from /opt/media/build/msdk/_studio/shared/include/mfxvideo++int.h:39,
                 from /opt/media/build/msdk/_studio/shared/include/mfx_common.h:25,
                 from /opt/media/build/msdk/_studio/mfx_lib/encode_hw/hevc/hevcehw_disp.cpp:21:
/usr/include/c++/5/bits/stl_pair.h:112:26: note: candidate: constexpr std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = const unsigned int; _T2 = std::unique_ptr<unsigned char []>]
       _GLIBCXX_CONSTEXPR pair(const _T1& __a, const _T2& __b)
                          ^
/usr/include/c++/5/bits/stl_pair.h:112:26: note:   no known conversion for argument 2 from 'unsigned char*' to 'const std::unique_ptr<unsigned char []>&'
/usr/include/c++/5/bits/stl_pair.h:108:26: note: candidate: constexpr std::pair<_T1, _T2>::pair() [with _T1 = const unsigned int; _T2 = std::unique_ptr<unsigned char []>]
       _GLIBCXX_CONSTEXPR pair()
                          ^
/usr/include/c++/5/bits/stl_pair.h:108:26: note:   candidate expects 0 arguments, 2 provided
_studio/mfx_lib/encode_hw/CMakeFiles/encode_hw.dir/build.make:830: recipe for target '_studio/mfx_lib/encode_hw/CMakeFiles/encode_hw.dir/hevc/hevcehw_disp.cpp.o' failed
make[2]: *** [_studio/mfx_lib/encode_hw/CMakeFiles/encode_hw.dir/hevc/hevcehw_disp.cpp.o] Error 1
make[2]: Leaving directory '/opt/media/build/msdk/__cmake_build'
CMakeFiles/Makefile2:2684: recipe for target '_studio/mfx_lib/encode_hw/CMakeFiles/encode_hw.dir/all' failed
make[1]: *** [_studio/mfx_lib/encode_hw/CMakeFiles/encode_hw.dir/all] Error 2
make[1]: Leaving directory '/opt/media/build/msdk/__cmake_build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/opt/media/build/msdk/__cmake_build'
```

**Comment by dvrogozh** [comment] 2019-12-12 20:19
@uartie : GNU GCC 5.4.0 has _experimental_ support for C++11. Please, update the compiler to be at least GCC-6 which has official support for C++11.

This is not an issue unless you will be able to reproduce it on the compiler w/ official support of C++11.

**Comment by uartie** [comment] 2019-12-12 20:24
Ubuntu Xenial does not provide any package for GNU GCC > 5.4.0, afaict.  If GCC-6 is required, then we should enforce that at _configure_ time.

**Comment by dvrogozh** [comment] 2019-12-12 20:48
I don't see much point to be too restrictive. There is a recommendation on the primary readme: https://github.com/Intel-Media-SDK/MediaSDK#recommendations. If someone wants to try on his own risk - why not? Though if we start to get things broken on gcc-5.4 even on compilation level we might indeed introduce a check.

**Comment by uartie** [comment] 2019-12-12 20:58
Please keep in mind that if the decision comes down to not fixing compilation with GCC 5.4, then it essentially means users of Ubuntu Xenial (which is not EOL until April 2021) are excluded from MSDK usage (i.e. going forward).  This might impact the ffmpeg and gstreamer plugins and their community processes (e.g. CI pipelines, etc).

**Comment by dvrogozh** [comment] 2019-12-12 21:15
Even if compiler can't be installed, it can be built. The problem with gcc below 6 is not only be able or not be able to compile, but also on how to support such a build? Unfortunately compiler bugs are possible and we will be denied from the fixes on compiler side for this very reason: support is experimental - update. In the end of the day there are previous releases of mediasdk which can be built with 5.4 and used. I think that the upcoming 2019'Q4 release won't have the changes which break 5.4 build and still will work. Next release in 2020'Q1 will be the one which will break build w/ 5.4 if nothing will be changed.

However, I don't mind if the change to fix 5.4 build is reasonably small. @eistarov : can you, please, evaluate? Also, please, double check that we did not break gcc-6 since if we did this will be indeed Critical.

**Comment by uartie** [comment] 2019-12-12 21:24
I do know for sure, that it still compiles fine on newer Ubuntu and Fedora distros (all with gcc >= 7.x).

**Comment by uartie** [comment] 2019-12-12 21:27
> ...In the end of the day there are previous releases of mediasdk which can be built with 5.4 and used... Next release in 2020'Q1 will be the one which will break build w/ 5.4 if nothing will be changed.

Right.  That is what I meant by "going forward".

**Comment by dvrogozh** [comment] 2019-12-12 21:30
Actually our CI checks gcc-6 along with gcc-9 and clang-9: https://github.com/Intel-Media-SDK/MediaSDK/wiki/Media-SDK-CI-build-configurations. So, we hopefully should be good with gcc-6 standpoint.

**Comment by uartie** [comment] 2019-12-12 21:45
FWIW, Ubuntu Xenial users can get GCC 6 via PPA repos  (http://www.riccardomariabianchi.com/updating-gcc-on-ubuntu.html).

**Comment by eistarov** [comment] 2019-12-13 12:01
#1838 should fix build with GCC5.4, but if we want to keep it alive we need it in CI at least.

**Comment by dmitryermilov** [comment] 2020-02-14 13:49
>#1838 should fix build with GCC5.4, but if we want to keep it alive we need it in CI at least.

@dvrogozh @onabiull , @eponomar could you comment?

**Closed** 2020-02-20 14:58 UTC
