### ISSUE TITLE
vc1d reports frame types incorrectly for some frames

### ISSUE THREAD

**Issue by dvrogozh** [Intel-Media-SDK/MediaSDK#1239] opened 2019-03-05 18:12 UTC
Follow up issue after #333. Per @lizhong1008 observations:

> Tested SA00040.vc1 and SA10091.vc1 (you can get all of them from ffmpeg suite: http://ffmpeg.org/fate.html). Two issues found:
> * No I frame exposed for SA00040.vc1. All frames reported as B frames.
> * Some last frames of SA10091.vc1 are still reported as Unknown.

@akokoshn : can you, please, continue debug?

**Comment by akokoshn** [comment] 2019-03-05 19:26
@dvrogozh , sure. I will check these streams

**Comment by akokoshn** [comment] 2019-03-07 15:04
Both issues were caused by wrong setting frame type for buffered frames.
Should be fixed by https://github.com/Intel-Media-SDK/MediaSDK/pull/1249 . @dvrogozh, please take a look.
A have compared frame types reported by SW VC1d and MSDK VC1d. For streams  SA00040 and SA10091 results same: IPPP..

**Closed** 2019-03-07 15:48 UTC
Labels: P1
