### ISSUE TITLE
TGL: sample_decode on av1 not working with system memory

### ISSUE THREAD

**Issue by SiewHoon** [Intel-Media-SDK/MediaSDK#2307] opened 2020-08-24 05:05 UTC
Failed to do AV1 decoding using system memory. Not issue with video memory.

Here is the media components stack:
Libva: 836d8e2a411ece2539d1e8046fa845912af8729a
Libva-utils: b4048ae967079414d385a88d5ef8d4bc676b6311
MSDK library: dbbb196d21a55c8666e1e5f153d5c5f251742f93 + https://github.com/Intel-Media-SDK/MediaSDK/pull/2276, 
Media Driver: 643873380fd71c7c072616a0a33a283972e385c6
Gmmlib: intel-gmmlib-20.2.4

Output: 
tgl-rvp05@test-tgl-rvp05:/usr/share/mfx/samples$ ./sample_decode av1 -i ~/Development/av1_test.ivf -o /dev/null
libva info: VA-API version 1.9.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_9
libva info: va_openDriver() returns 0
Decoding Sample Version 8.4.27.0

Input video     AV1
Output format   NV12
Input:
  Resolution    640x480
  Crop X,Y,W,H  0,0,640,480
Output:
  Resolution    640x480
Frame rate      1.00
Memory type             system
MediaSDK impl           hw
MediaSDK version        1.34

Decoding started
Frame number:   34, fps: 887.752, fread_fps: 0.000, fwrite_fps: 9073.926
[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), RunDecoding, Unexpected error!! at /home/tgl-rvp05/Development/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:2034

ERROR: Hardware device was lost or returned unexpected error. Recovering...
Frame number:   34, fps: 771.028, fread_fps: 0.000, fwrite_fps: 9073.926
[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), RunDecoding, Unexpected error!! at /home/tgl-rvp05/Development/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:2034

ERROR: Hardware device was lost or returned unexpected error. Recovering...
Frame number:   34, fps: 719.227, fread_fps: 0.000, fwrite_fps: 9073.926
[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), RunDecoding, Unexpected error!! at /home/tgl-rvp05/Development/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:2034

ERROR: No input data was consumed since last reset. Quitting to avoid looping forever.

Decoding finished

**Comment by guowillyy** [comment] 2020-09-27 03:32
Issue was root caused as DoFastCopy is not added thread safety protection, code review WIP.

**Comment by dmitryermilov** [comment] 2020-09-30 21:55
@guowillyy , I'm skeptical this is correct.
Could you provide investigation results? 
Why does DoFastCopy work fine for other decoders?

**Comment by xhaihao** [comment] 2020-11-16 06:58
@wangyan-intel @dmitryermilov Any update for this issue?

**Comment by wangyan-intel** [comment] 2020-11-16 07:00
@weizhu-intel Could you please double check if your patch has been merged into upstream? Thanks.

**Comment by weizhu-intel** [comment] 2020-11-16 08:14
@xhaihao You can cherry pick this PR(#2486) to have a try on local.

**Comment by xhaihao** [comment] 2020-11-17 06:17
@weizhu-intel it works well after applying #2486

**Comment by wangyan-intel** [comment] 2020-11-23 08:29
#2486 hase been merged. Close this issue based on @xhaihao's comments.

**Closed by wangyan-intel** 2020-11-23 08:29 UTC
Labels: decode
