### ISSUE TITLE
Unexpected result of DecodeFrameAsync

### ISSUE THREAD

**Issue by filippenkos** [Intel-Media-SDK/MediaSDK#1740] opened 2019-10-21 15:09 UTC
In case of submitting maximum number of surfaces to decoder during flushing (working with preallocated hardware memory), when calling DecodeFrameAsync with NULL bit stream, NULL work surface and valid sync point we get not NULL surface with pointer not matching to any of the pointers of preallocated buffers.

**Comment by dmitryermilov** [comment] 2019-10-31 07:55
Hi @filippenkos ,

Which decoder? Could you provide a reproducer?

**Comment by dmitryermilov** [comment] 2019-11-08 14:41
@filippenkos , can you please reply?

**Comment by filippenkos** [comment] 2019-11-08 14:49
Hi @dmitryermilov ,
Sorry for late reply. It happens only with MPEG2 decoder. We couldn't provide a reproducer.

**Comment by dmitryermilov** [comment] 2019-11-27 11:25
Closing this since it's under offline discussion.

**Closed by dmitryermilov** 2019-11-27 11:25 UTC
