### ISSUE TITLE
Failed to Decode H264 at i7-8700k

### ISSUE THREAD

**Issue by zhoub** [Intel-Media-SDK/MediaSDK#1470] opened 2019-06-05 08:38 UTC
```
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.4.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Coffee Lake - 2.2.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSlice
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

Used the sample_decode from tag 19.1.0 
```bash
./sample_decode h264 -i ~/Downloads/IAmLegendFHD_Main.h264
```
```
libva info: VA-API version 1.4.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), AllocFrames, m_pmfxDEC->QueryIOSurf failed at /home/zb/Development/MediaSDK-repo/samples/sample_decode/src/pipeline_decode.cpp:1036

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, AllocFrames failed at /home/zb/Development/MediaSDK-repo/samples/sample_decode/src/pipeline_decode.cpp:429

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/zb/Development/MediaSDK-repo/samples/sample_decode/src/sample_decode.cpp:681
zb@etna:~/Development/MediaSDK-build/dist-19.1.0/share/mfx/samples$ ./sample_decode h264 -i ~/Downloads/IAmLegendFHD_Main.h264 -sw

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_mfxSession.Init failed at /home/zb/Development/MediaSDK-repo/samples/sample_decode/src/pipeline_decode.cpp:296

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /home/zb/Development/MediaSDK-repo/samples/sample_decode/src/sample_decode.cpp:681
```

**Comment by zhoub** [comment] 2019-06-05 09:19
I think it's inside
```
mfxStatus VAAPIVideoCORE::IsGuidSupported(const GUID guid,
                                         mfxVideoParam *par, bool isEncoder)
```

Around the logic of locating the proper VA profile and entrypoint.

**Comment by zhoub** [comment] 2019-06-05 09:38
Fast fix.

At least now sample_decode works...

```diff
diff --git a/_studio/shared/src/libmfx_core_vaapi.cpp b/_studio/shared/src/libmfx_core_vaapi.cpp
index 2944f57..328541c 100644
--- a/_studio/shared/src/libmfx_core_vaapi.cpp
+++ b/_studio/shared/src/libmfx_core_vaapi.cpp
@@ -1300,7 +1300,7 @@ void VAAPIVideoCORE::ReleaseHandle()
 //function checks profile and entrypoint and video resolution support
 //On linux specific function!
 mfxStatus VAAPIVideoCORE::IsGuidSupported(const GUID guid,
-                                         mfxVideoParam *par, bool /* isEncoder */)
+                                         mfxVideoParam *par, bool isEncoder)
 {
     MFX_CHECK(par, MFX_WRN_PARTIAL_ACCELERATION);
     MFX_CHECK(!IsMVCProfile(par->mfx.CodecProfile), MFX_WRN_PARTIAL_ACCELERATION);
@@ -1308,9 +1308,43 @@ mfxStatus VAAPIVideoCORE::IsGuidSupported(const GUID guid,
     MFX_CHECK(m_Display, MFX_ERR_DEVICE_FAILED);
 
 #if VA_CHECK_VERSION(1, 2, 0)
+    VAProfile req_profile = VAProfileNone;
+    VAEntrypoint req_entrypoint = static_cast<VAEntrypoint>(0);
+
     VaGuidMapper mapper(guid);
-    VAProfile req_profile = mapper.profile;
-    VAEntrypoint req_entrypoint = mapper.entrypoint;
+    if (isEncoder)
+    {
+        req_profile = mapper.profile;
+        req_entrypoint = mapper.entrypoint;
+    }
+    else
+    {
+        switch (par->mfx.CodecId)
+        {
+        case MFX_CODEC_AVC:
+        {
+            if (par->mfx.CodecProfile == MFX_PROFILE_AVC_CONSTRAINED_BASELINE)
+            {
+                req_profile = VAProfileH264ConstrainedBaseline;
+            }
+            else if (par->mfx.CodecProfile == MFX_PROFILE_AVC_MAIN)
+            {
+                req_profile = VAProfileH264Main;
+            }
+            else if (par->mfx.CodecProfile == MFX_PROFILE_AVC_HIGH)
+            {
+                req_profile = VAProfileH264High;
+            }
+
+            break;
+        }
+        default:
+            return MFX_ERR_UNSUPPORTED;
+        }
+
+        req_entrypoint = VAEntrypointVLD;
+    }
+
     mfxI32 va_max_num_entrypoints = vaMaxNumEntrypoints(m_Display);
     mfxI32 va_max_num_profiles = vaMaxNumProfiles(m_Display);
     MFX_CHECK_COND(va_max_num_entrypoints && va_max_num_profiles);
@@ -1341,22 +1375,26 @@ mfxStatus VAAPIVideoCORE::IsGuidSupported(const GUID guid,
     auto it_entrypoint = find(va_entrypoints.begin(), va_entrypoints.end(), req_entrypoint);
     MFX_CHECK(it_entrypoint != va_entrypoints.end(), MFX_ERR_UNSUPPORTED);
 
-    VAConfigAttrib attr[] = {{VAConfigAttribMaxPictureWidth,  0},
-                             {VAConfigAttribMaxPictureHeight, 0}};
+    //check encoding maximal resolution.
+    if (isEncoder)
+    {
+        VAConfigAttrib attr[] = {{VAConfigAttribMaxPictureWidth,  0},
+                                 {VAConfigAttribMaxPictureHeight, 0}};
 
-    //ask driver about support
-    va_sts = vaGetConfigAttributes(m_Display, mapper.profile,
-                                   mapper.entrypoint,
-                                   attr, sizeof(attr)/sizeof(*attr));
+        //ask driver about support
+        va_sts = vaGetConfigAttributes(m_Display, isEncoder ? mapper.profile : req_profile,
+                                       isEncoder ? mapper.entrypoint : req_entrypoint,
+                                       attr, sizeof(attr)/sizeof(*attr));
 
-    MFX_CHECK(va_sts == VA_STATUS_SUCCESS, MFX_ERR_UNSUPPORTED);
+        MFX_CHECK(va_sts == VA_STATUS_SUCCESS, MFX_ERR_UNSUPPORTED);
 
-    //check resolution video
-    MFX_CHECK(attr[0].value != VA_ATTRIB_NOT_SUPPORTED, MFX_ERR_UNSUPPORTED);
-    MFX_CHECK(attr[1].value != VA_ATTRIB_NOT_SUPPORTED, MFX_ERR_UNSUPPORTED);
-    MFX_CHECK_COND(attr[0].value && attr[1].value);
-    MFX_CHECK(attr[0].value >= par->mfx.FrameInfo.Width, MFX_ERR_UNSUPPORTED);
-    MFX_CHECK(attr[1].value >= par->mfx.FrameInfo.Height, MFX_ERR_UNSUPPORTED);
+        //check resolution video
+        MFX_CHECK(attr[0].value != VA_ATTRIB_NOT_SUPPORTED, MFX_ERR_UNSUPPORTED);
+        MFX_CHECK(attr[1].value != VA_ATTRIB_NOT_SUPPORTED, MFX_ERR_UNSUPPORTED);
+        MFX_CHECK_COND(attr[0].value && attr[1].value);
+        MFX_CHECK(attr[0].value >= par->mfx.FrameInfo.Width, MFX_ERR_UNSUPPORTED);
+        MFX_CHECK(attr[1].value >= par->mfx.FrameInfo.Height, MFX_ERR_UNSUPPORTED);
+    }
 
     return MFX_ERR_NONE;
 #else
```

**Comment by zhoub** [comment] 2019-06-05 09:50
https://github.com/zhoub/MediaSDK/commit/73b62b5816bdf42f468e74181e501348cf50228c

**Comment by catid** [comment] 2020-04-07 21:09
Thanks!  This fixed it for me too.  My environment is Ubuntu 18.04 kernel 4.18.0-25, building intel-media-sdk, libva, libdrm via Nix package manager, and then executing my test like this to reference the Ubuntu libs:

`
# Create /run/opengl-driver/lib/dri symlink:
sudo mkdir /run/opengl-driver/
sudo mkdir /run/opengl-driver/lib
sudo ln -s /usr/lib/x86_64-linux-gnu/dri/ /run/opengl-driver/lib/dri 

# Run my test with LD_PRELOAD:
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1:/usr/lib/x86_64-linux-gnu/libdrm.so.2:/usr/lib/x86_64-linux-gnu/libpciaccess.so.0:/lib/x86_64-linux-gnu/libz.so.1 ./mfx_test`

**Comment by Gvence** [comment] 2020-11-04 02:17
I already merged in. Can be closed.

**Comment by wangyan-intel** [comment] 2020-11-04 02:37
@zhoub Could you please provide your clip for double check and your change to PR for reviewing. If it has no the other concern, we can merge it. Thanks.

**Comment by wangyan-intel** [comment] 2020-11-05 02:58
@zhoub I tried some AVC clips (baseline/main/high profile) in my hand based on the latest MSDK sample_decode. I cannot reproduce your issue. It may have been fixed. So I close this issue now. If you have this issue without your change, please free to reopen this issue and provide your clip. Thanks.

**Closed by wangyan-intel** 2020-11-05 02:58 UTC
Labels: decode
