### ISSUE TITLE
sample_decode failed using drm render

### ISSUE THREAD

**Issue by MemeTao** [Intel-Media-SDK/MediaSDK#1622] opened 2019-09-04 01:48 UTC
./sample_decode h264 -i ./input.h264 -hw -vaapi -calc_latency -async 1 -rdrm
libva info: VA-API version 1.6.0
libva info: va_getDriverName() returns 1
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
get chip id failed: -1 [13]
param: 4, val: 0
libva error: /usr/local/lib/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 18
------------------------------------------------------------------------------------------------------------------------
1. what's the difference between -r and -rdrw?  '-r' work well on my pc.
2. x-windows is not necessary in 'DRM' mode?
3 'DRM' mode perform better?

**Comment by NaveenKumar-Intel** [comment] 2019-09-10 06:32
@MemeTao,
I can able to reproduce this issue on CL platform. 
Based on the analysis, this issue is due to the DRM mode selection when "rdrm" parameter is used with sample_decode command line. 
when "rdrm" param is used, it creates **"/dev/dri/card0"** GPU node where as it creates **"/dev/dri/renderD128"** in general case.
When "rdrm" param is used, it specifies **pParams->libvaBackend = MFX_LIBVA_DRM_MODESET**. When we change this param  to **MFX_LIBVA_DRM**, the issue is not reproducing and decoding just works fine.

Moreover, for **Gen GPU architecture**, it always supports **/dev/dri/renderD128** node not **/dev/dri/card0**.
Please find reference in the source code: file /media-driver/media_driver/linux/common/ddi/media_libva_util.h
**#define DEVICE_NAME "/dev/dri/renderD128"   // For Gen, it is always /dev/dri/renderD128 node**

Thanks,
NaveenKumar

**Comment by dvrogozh** [comment] 2019-09-11 22:48
drm rendering mode (-rdrm) is the one which should work _without_ any graphical server (like X server or Wayland) running. So, basically that's direct framebuffer rendering when you have display, but work on a server-like installation without X running. For that reason it opens /dev/dri/card0 since it performs mode setting and actual real drm authentication rather than x11 authentication. Mind: if X server or Wayland is running -rdrm was not supposed to work at all. Instead you should use -r.

-r is usual rendering mode under X Server. 

@MemeTao, @NaveenKumar-Intel : did you try -rdrm under X server running?

**Comment by NaveenKumar-Intel** [comment] 2019-09-17 05:50
Hi @dvrogozh,
Earlier, we have verified on ClearLinux with –rdrm by running Wayland. As you have suggested, -rdrm should not be used when x11 server and wayland are running. So PR raised makes no use.
However when we are trying without wayland, sample_decode is failing when drmRenderer tries to allocate memory while invoking function drmModeAddFB() IOCTL. We haven't debugged this further why DRM IOCTL is failing.
Observed that the selected memory type is MEM_TYPE_KERNEL_DRM.
Please let us know your inputs on this.

**Comment by dvrogozh** [comment] 2019-09-17 14:20
Hi, I vaguely remember that to actually be able to render under frame buffer you need to use correct color format since scan out is not supported from all color formats. I would suggest to try with the combination `-rdrm -rgb4` to get one of RGB color formats instead of NV12 on the output. Can you, please, try that?

**Comment by dvrogozh** [comment] 2019-09-17 14:22
BTW, for wayland you should use -rwld for the rendering. -rgb4 might also be needed (as well as for x11 w/ DRI3) if path uses direct scanout.

**Comment by NaveenKumar-Intel** [comment] 2019-09-20 06:35
Hi @MemeTao , @dvrogozh ,

Observed that drm rendering works fine when no graphical server running (such as X server or Wayland). 

Also observed that drm rendering under frame buffer works only with **-rgb4** (RGB) color format & not with default NV12. As shown in the following command line **drm rendering works fine**: 

`/usr/share/mfx/samples/sample_decode h264 -i 1080p_30fps.h264 -hw -vaapi -calc_latency –rdrm -rgb4`

Found that drm rendering fails with –async 1 ( as @MemeTao uses) in the above pipeline, it is failing to find available surfaces as shown in the following error logs:

`root@clr-31ce3df6fc9142bba096c1aa5890c202 /tmp # /usr/share/mfx/samples/sample_decode h264 -i 1080p_30fps.h264 -hw -vaapi -calc_latency -async 1 -rgb4 -rdrm
pretending that aspect ratio is 1:1
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_4
libva info: va_openDriver() returns 0
drmrender: trying connection: HDMIA
drmrender: selected crtc already attached to connector
drmrender: succeeded...
drmrender: connected via HDMIA to 1920x1080@60 capable display
Decoding Sample Version 8.4.27.

Input video     AVC
Output format   RGB4 (using vpp)
Input:
  Resolution    1920x1088
  Crop X,Y,W,H  0,0,1920,1080
Output:
  Resolution    1920x1080
Frame rate      30.00
Memory type             vaapi
MediaSDK impl           hw
MediaSDK version        1.29

Decoding started
drmrender: warning: rendering via OVERLAY plane
**fatal: failed to find output surface, that's a bug!**
Frame    1, latency=91.74500 ms, fread_fps: 0.000, fwrite_fps: 154.107

Latency summary:
AVG=91.74500 ms, MAX=91.74500 ms, MIN=91.74500 ms
[ERROR], sts=MFX_ERR_NOT_FOUND(-9), RunDecoding, Unexpected error!! at /home/naveen/workspace/bkup_GP-2.0/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:1900

[ERROR], sts=MFX_ERR_NOT_FOUND(-9), main, Pipeline.RunDecoding failed at /home/naveen/workspace/bkup_GP-2.0/MediaSDK/samples/sample_decode/src/sample_decode.cpp:740
drmrender: failed to restore original mode
drmrender: warning: failure to restore original mode may lead to application segfault!
root@clr-31ce3df6fc9142bba096c1aa5890c202 /tmp #
`

When async value is mentioned as 1, it creates only 1 surface at a time which is already acquired for rendering. And as there is no other surfaces available, it is failing with the above mentioned error. 

**However if we change the async value other than 1 (>1) then rendering is happening.**

**Comment by dmitryermilov** [comment] 2019-12-11 22:36
It should be addressed by https://github.com/Intel-Media-SDK/MediaSDK/pull/1798. Please re-open if needed.

**Closed by dmitryermilov** 2019-12-11 22:36 UTC

**Comment by mamathakempeli** [comment] 2021-11-02 14:38
@dvrogozh ,
As you told,  if X server or Wayland is running -rdrm was not supposed to work.
in my PC server X11 is running, please let me know how to change it to DRM or how to stop X server.

**Comment by dmitryermilov** [comment] 2021-11-02 19:24
> @dvrogozh , As you told, if X server or Wayland is running -rdrm was not supposed to work. in my PC server X11 is running, please let me know how to change it to DRM or how to stop X server.

@mamathakempeli , there're many resources on the Internet explaining how to stop/kill X server.

**Comment by mamathakempeli** [comment] 2021-11-09 07:24
@NaveenKumar-Intel 

As you suggested, I have changed the pParams->libvaBackend = MFX_LIBVA_DRM_MODESET param to MFX_LIBVA_DRM, now decoding is working fine, but video is not displaying. 

I am getting the logs as below, and terminating without video display, 

mamatha@Rental32-LaptopU:~/msdk/build/__bin/release$ ./sample_decode h264 -i h264.h264 -window 0 0 640 1270 -vaapi -calc_latency -async 4  -nv12 -rdrm
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
libva info: va_openDriver() returns 0
pretending that stream is 30fps one
pretending that aspect ratio is 1:1
Decoding Sample Version 8.4.27.0


Input video	AVC 
Output format	NV12 (using vpp)
Input:
  Resolution	640x480
  Crop X,Y,W,H	0,0,640,480
Output:
  Resolution	640x1270
Frame rate	30.00
Memory type		vaapi
MediaSDK impl		hw
MediaSDK version	1.32

Decoding started
Frame    1, latency=43.78700 ms44, fread_fps: 0.000, fwrite_fps: 0.000
Frame    2, latency=44.62600 ms
.
.
.
.
.
.
.
Frame  247, latency=163.93700 ms
Frame  248, latency=164.25700 ms
Frame  249, latency=164.35100 ms
Frame  250, latency=164.57500 ms

Latency summary:

AVG=113.48100 ms, MAX=164.57500 ms, MIN=43.78700 ms
Decoding finished


What i have to do to get video display of given sample.
