### ISSUE TITLE
HEVC green video when bit stream contains a missing frame

### ISSUE THREAD

**Issue by Mortvola** [Intel-Media-SDK/MediaSDK#2380] opened 2020-09-24 14:58 UTC
We are seeing a large amount of distortion with green chroma when the bit stream has a missing frame. This is very problematic when using the HEVC decoder for video conferencing.

In the attached zip file, please find the test bit stream that has the second frame missing. In addition, I have included the yuv file that was produced by sample_decode.

The sample_decode command line I used:
./sample_decode h265 -i ./record-missing.h265 -o record-missing.yuv -nv12

The gstreamer pipeline I used to display the sample_decode output file:
gst-launch-1.0 -v filesrc location=./record-missing.yuv ! rawvideoparse format=nv12 framerate=1/2 width=1024 height=576 ! glimagesink

Let me know if there is any additional information needed.

Ideally, I think the decoder should use the last decoded reference frame as the reference instead of what ever it is trying to use. I've been going through the source for the H265 decoder in the media SDK but I have yet to figure out if I can modify the code to have it use the previous reference frame. Any guidance here would be appreciated.

Thanks,
Richard

[record-missing.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/5276958/record-missing.zip)

**Comment by daleksan** [comment] 2021-06-09 22:10
Hi @wangyan-intel can you take a look?

**Comment by wangyan-intel** [comment] 2021-06-11 00:50
@chuanli1 Could please take a look? Thanks.

**Comment by chuanli1** [comment] 2021-06-11 00:54
ok, I'll take a look.

**Comment by Gvence** [comment] 2022-04-06 07:04
Hi, have a quick check of this clip. It should be a error clip, there are some missing frames in stream. In Media SDK, it will output 00 if the data buffer has no info. In YUV view, it should be green. So, it's should related to no value in bitstream.  
For your comment, we won't add new feature in Media SDK legacy side. We will set this problem as a expected behavior due to your input stream is an error clip.
![difference](https://user-images.githubusercontent.com/32268352/161915017-d9c59a30-cd2a-46ba-8fe3-13ededb7a7e3.PNG)

**Comment by wangyan-intel** [comment] 2022-04-06 07:49
@Mortvola I will close this issue at first. Please free to reopen it if necessary. Thanks.

**Closed by wangyan-intel** 2022-04-06 07:49 UTC
Labels: decode
