### ISSUE TITLE
RGB32->RGB32 composition with tile has incorrect result

### ISSUE THREAD

**Issue by joojler** [Intel-Media-SDK/MediaSDK#2164] opened 2020-06-16 01:11 UTC
with 2019 R4 release on Ubuntu 18.04 sample_multi_transcode, if we use RGB32->RGB32 for composition with tiles, there will be some garbge between the input videos.  if we use NV12->RGB32 for composition even also with tiles, no issues. 

![image](https://user-images.githubusercontent.com/3134283/84720631-24d17380-afb1-11ea-8cad-e59e29a8074f.png)

will attach the par file later.

**Comment by FurongZhang** [comment] 2020-06-18 02:18
Could it be Surface pitch alignment?

**Comment by FurongZhang** [comment] 2020-07-14 06:47
@joojler , where is the par file? If you have rooted cause this issue as we discussed offline, could I close this issue? Thanks a lot in advance!

**Comment by joojler** [comment] 2020-07-20 07:09
Hi Furong, this is the par file i used. 

-i::h264 /home/work/video/3.h264 -join -hw -dec_postproc -async 4 -o::sink -vpp_comp_dst_x 200 -vpp_comp_dst_y 100 -vpp_comp_dst_w 560 -vpp_comp_dst_h 340 -ext_allocator -vpp_comp_tile_id 0
-i::h264 /home/work/video/3.h264 -join -hw -dec_postproc -async 4 -o::sink -vpp_comp_dst_x 1160 -vpp_comp_dst_y 100 -vpp_comp_dst_w 560 -vpp_comp_dst_h 340 -ext_allocator -vpp_comp_tile_id 0
-i::h264 /home/work/video/4.h264 -join -hw -dec_postproc -async 4 -o::sink -vpp_comp_dst_x 200 -vpp_comp_dst_y 640 -vpp_comp_dst_w 560 -vpp_comp_dst_h 340 -ext_allocator -vpp_comp_tile_id 1
-i::h264 /home/work/video/4.h264 -join -hw -dec_postproc -async 4 -o::sink -vpp_comp_dst_x 1160 -vpp_comp_dst_y 640 -vpp_comp_dst_w 560 -vpp_comp_dst_h 340 -ext_allocator -vpp_comp_tile_id 1
-vpp_comp_num_tiles 2 -vpp_comp_only 4 -w 1920 -h 1080 -async 4 -threads 2 -join -hw  -i::source -ext_allocator -ec::rgb4 -rdrm-HDMIA

**Comment by FurongZhang** [comment] 2020-08-10 13:03
Assigned this issue to Jason.

**Comment by yuqinw** [comment] 2020-08-27 02:07
Hi joojler,

I am focused on this issue mainly, so could you give me 3.h264 and 4.h264 files?

**Comment by yuqinw** [comment] 2020-10-19 02:07
hi all, 
the root  cause is output_background_color unset, and I submit the patch at: https://git-ccr-1.devtools.intel.com/gerrit/#/c/182217/ 
After syncing with James, the issue is fixed, but maybe need more test cases to verify. thanks.

**Comment by FurongZhang** [comment] 2020-10-19 05:14
Rooted caused by @yuqinw .

**Comment by FurongZhang** [comment] 2020-10-19 11:44
https://github.com/Intel-Media-SDK/MediaSDK/commit/18781d3be243748b9b80f5055401c1fa402353f6 fixed this issue and merged.

**Comment by FurongZhang** [comment] 2020-10-19 11:44
Hence close this issue. Please feel free to let us know if any further questions.

**Closed by FurongZhang** 2020-10-19 11:44 UTC
Labels: vpp
