### ISSUE TITLE
[overlay_qsv] Unsupported pixel format: bgra

### ISSUE THREAD

**Issue by nyanmisaka** [Intel-Media-SDK/MediaSDK#2031] opened 2020-03-22 07:16 UTC
This issue **only occurs on Windows** when burning in graphical subtitles into a video using ffmpeg `overlay_qsv` filter. The same command **works fine on Linux**.

Seems that there are some issues when handling bgra formart by using `hwupload=extra_hw_frames` with `overlay_qsv`. Unless I convert subtitles to nv12 format, it will report an error, but this will lose the alpha channel and will corrupt the output video. 

Same issues here https://software.intel.com/en-us/node/801004

- Context:
HD630 iGPU 
ffmpeg [4.3-git](https://ffmpeg.zeranoe.com/builds/win64/shared/) 
Windows 10 19H2
the lastest driver 26.20.100.7870

- FFmpeg cli:
`ffmpeg.exe -hwaccel qsv -c:v h264_qsv -i file:"simple.mkv" -i file:"subtitle.sub" -map 0:0 -map 0:1 -codec:v:0 h264_qsv -filter_complex "[1:0]scale=1920:1080,hwupload=extra_hw_frames=64[sub];[0:0][sub]overlay_qsv=x=(W-w)/2:y=(H-h)/2,scale_qsv=w=1280:h=720:format=nv12" -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000  -copyts -avoid_negative_ts disabled -y "out.mp4"`

- Error msg:
```
Stream mapping:
  Stream #0:0 (h264_qsv) -> overlay_qsv:main (graph 0)
  Stream #1:0 (pgssub) -> scale (graph 0)
  scale_qsv (graph 0) -> Stream #0:0 (h264_qsv)
  Stream #0:1 -> #0:1 (dts (dca) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
[matroska,webm @ 000002636b5f47c0] sub2video: using 1920x1080 canvas
[AVHWFramesContext @ 000002636d35c980] Unsupported pixel format: bgra
[AVHWFramesContext @ 000002636d35c980] Error creating an internal frame pool
[AVHWFramesContext @ 000002636d35bb00] Error initializing a child frames context
[AVHWFramesContext @ 000002636d35bb00] Error creating an internal frame pool
[Parsed_hwupload_1 @ 000002636d367e80] Failed to configure output pad on Parsed_hwupload_1
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[libmp3lame @ 000002636d258a40] 3 frames left in the queue on closing
Conversion failed!
```

**Comment by dmitryermilov** [comment] 2020-03-22 20:06
@FurongZhang , please investigate

**Comment by daleksan** [comment] 2020-10-15 10:51
@FurongZhang any ETA?

**Comment by FurongZhang** [comment] 2020-10-15 14:12
@Yanfeng-mi, please provide ETA. Thanks a lot in advance!

**Comment by MicroYY** [comment] 2020-10-20 03:04
Hi， I‘m investigating this issue. Would you pls share the test assets to me so that I can reproduce this issue?

**Comment by nyanmisaka** [comment] 2020-10-20 05:37
@MicroYY Thanks for your response. 
The PGSSUB graphical subtitle is from a movie. It may take some time to download.
https://imisaka.xyz:8089/s/8ddBFBm5Q8WgQX2



[0:v] means video track and [0:s] means subtitle track.
Works on Linux but throw bgra error on Windows.
`
ffmpeg -init_hw_device qsv -c:v hevc_qsv -i "Tamako love story (2014).mkv" -c:v h264_qsv -b:v 5000000 -profile:v high -level 41 -an -sn -vsync -1 -start_at_zero -copyts -avoid_negative_ts 0 -filter_complex "[0:s]scale=1920x1080,hwupload=extra_hw_frames=64[sub];[0:v]hwupload=extra_hw_frames=64,vpp_qsv=w=1920:h=1080:format=nv12[base];[base][sub]overlay_qsv" -y output.mp4
`

Force convert subtitle to nv12. ffmpeg works but the alpha channel is lost. For testing only.
`
ffmpeg -init_hw_device qsv -c:v hevc_qsv -i "Tamako love story (2014).mkv" -c:v h264_qsv -b:v 5000000 -profile:v high -level 41 -an -sn -vsync -1 -start_at_zero -copyts -avoid_negative_ts 0 -filter_complex "[0:s]scale=1920x1080,format=nv12,hwupload=extra_hw_frames=64[sub];[0:v]hwupload=extra_hw_frames=64,vpp_qsv=w=1920:h=1080:format=nv12[base];[base][sub]overlay_qsv=alpha=90" -y output.mp4
`

**Comment by MicroYY** [comment] 2020-10-22 15:14
@nyanmisaka 
The driver log and trace of MSDK  has been dumped, but there is no unexpected behavior from them.  
Since the driver does support BGRA, it's supposed that FFMPEG has no support for this format.
I am trying to figure out whether FFMPEG attributes to this issue.

**Comment by FurongZhang** [comment] 2020-10-26 13:28
@microYY, could we check if sample vpp or vpp sample code in toturial support this BGRA? If our sample code support it, then we can share our sample code on the GitHub. Thanks.

**Comment by MicroYY** [comment] 2020-10-27 09:00
> @MicroYY, could we check if sample vpp or vpp sample code in toturial support this BGRA? If our sample code support it, then we can share our sample code on the GitHub. Thanks.

Ok, I'll have a try.

**Comment by FurongZhang** [comment] 2020-10-29 11:18
@nyanmisaka, are you familiar with FFMPEG? According to our understanding, bgra in FFmpeg, argb in driver and rgb4 in MediaSDK are the same format. 

Now, we are suspecting FFMPEG supported format missed bgra format. https://github.com/FFmpeg/FFmpeg/blob/ae9a1a96982669926a4ecb92b066814f5f27dc38/libavutil/hwcontext_dxva2.c#L82
supported_formats[] = {
    { MKTAG('N', 'V', '1', '2'), AV_PIX_FMT_NV12 },
    { MKTAG('P', '0', '1', '0'), AV_PIX_FMT_P010 },
    { D3DFMT_P8,                 AV_PIX_FMT_PAL8 },
};

Can you please take a look from FFMPEG side? Thanks a lot in advance!

**Comment by FurongZhang** [comment] 2020-10-29 11:22
Trending to be a FFMPEG issue, not MSDK issue.

**Comment by nyanmisaka** [comment] 2020-10-29 12:12
> @nyanmisaka, are you familiar with FFMPEG? According to our understanding, bgra in FFmpeg, argb in driver and rgb4 in MediaSDK are the same format.
> 
> Now, we are suspecting FFMPEG supported format missed bgra format. https://github.com/FFmpeg/FFmpeg/blob/ae9a1a96982669926a4ecb92b066814f5f27dc38/libavutil/hwcontext_dxva2.c#L82
> supported_formats[] = {
> { MKTAG('N', 'V', '1', '2'), AV_PIX_FMT_NV12 },
> { MKTAG('P', '0', '1', '0'), AV_PIX_FMT_P010 },
> { D3DFMT_P8, AV_PIX_FMT_PAL8 },
> };
> 
> Can you please take a look from FFMPEG side? Thanks a lot in advance!

After adding `{ MKTAG('B', 'G', 'R', 'A'), AV_PIX_FMT_BGRA },` into `supported_formats`, the `IDirectXVideoAccelerationService_CreateSurface` failed to create bgra surfaces.
https://github.com/FFmpeg/FFmpeg/blob/ae9a1a96982669926a4ecb92b066814f5f27dc38/libavutil/hwcontext_dxva2.c#L194

But bgra is possible in VAAPI. https://github.com/FFmpeg/FFmpeg/blob/ae9a1a96982669926a4ecb92b066814f5f27dc38/libavutil/hwcontext_vaapi.c#L129

```
[AVHWFramesContext @ 000001df87527c40] Could not create the surfaces
[AVHWFramesContext @ 000001df87527c40] Error creating an internal frame pool
[AVHWFramesContext @ 000001df875286c0] Error initializing a child frames context
[AVHWFramesContext @ 000001df875286c0] Error creating an internal frame pool
[Parsed_hwupload_1 @ 000001df821dee00] Failed to configure output pad on Parsed_hwupload_1
Error reinitializing filters!
Failed to inject frame into filter network: Unknown error occurred
Error while processing the decoded data for stream #0:0
```

**Comment by nyanmisaka** [comment] 2020-10-29 16:18
@FurongZhang 
There is one more question.

As I see that `tonemap_vaapi` filter have been implemented in ffmpeg 4.3.
Then I tried it to do H2S for my HDR videos on a KabyLake chip(HD 630), ffmpeg works with no error but the output color doesn’t seem to have been changed at all.

Note that the software tonemap filter and tonemap_opencl filter are all works for this video.
I am using libva 2.8 and media-driver 20.2 comes with Ubuntu 20.10.
The 4k HDR sample is from https://4kmedia.org/sony-food-fizzle-uhd-hdr-4k-demo/

HDR has been enabled in iHD driver for KBL.
https://github.com/intel/media-driver/commit/c82f434c7ba97de08174736a654e5acfe8d67099
Does Kabylake chips support HDR Tonemapping? Thanks in advance!


```
ffmpeg -hwaccel vaapi -hwaccel_output_format vaapi \
-vaapi_device /dev/dri/renderD128 -i HDR.mp4 -c:v h264_vaapi \
-b:v 8000000 -level 41 -profile:v high -an -sn \
-vf 'scale_vaapi=w=1920:h=1080,tonemap=t=bt709:format=nv12' \
-y /tmp/SDR.mp4
```

**Comment by nyanmisaka** [comment] 2020-10-31 07:26
> @nyanmisaka
> Hi!
> Could you pls try `{ D3DFMT_A8R8G8B8, AV_PIX_FMT_BGRA},`?
> It works in my local env. Seems `MKTAG('B', 'G', 'R', 'A')` is not a valid d3d_format.
> Thanks!

That worked basically. But the burned-in subtitles is not sync with the video.
I tried to change the framesync options in `overlay_qsv` filter but the subtitles still flicker frequently.
This never happened on Linux with same commands.

ffmpeg win64 binary with d3d bgra patch: [ffmpeg1031.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/5468645/ffmpeg1031.zip)

```
ffmpeg -init_hw_device qsv -c:v hevc_qsv -i "Tamako love story (2014).mkv" -c:v h264_qsv -b:v 5000000 -profile:v high -level 41 -an -sn -vsync -1 -start_at_zero -copyts -avoid_negative_ts 0 -filter_complex "[0:s]scale=1920x1080,hwupload=extra_hw_frames=64[sub];[0:v]hwupload=extra_hw_frames=64,vpp_qsv=w=1920:h=1080:format=nv12[base];[base][sub]overlay_qsv" -y output.mp4
```

**Comment by MicroYY** [comment] 2020-10-31 12:49
There are two new issues now:
1. The substream is not sync with the mainstream (The subtitle flickers frequently,).
2. The program will stop suddenly at runtime (Seems cannot predict when will stop).
Did you encounter the second issue?

**Comment by nyanmisaka** [comment] 2020-11-01 12:24
> There are two new issues now:
> 
> 1. The substream is not sync with the mainstream (The subtitle flickers frequently,).
> 2. The program will stop suddenly at runtime (Seems cannot predict when will stop).
>    Did you encounter the second issue?

Only the first issue for me.
```
[hevc_qsv @ 000002bba5bfcfc0] A decode call did not consume any data: expect more data at input (-10)
    Last message repeated 2 times
102975967 frame duplication too large, skipping
frame=120642 fps= 87 q=11.0 Lsize= 2853173kB time=01:23:50.19 bitrate=4646.6kbits/s dup=0 drop=1 speed=3.61x
video:2853173kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
```

**Comment by FurongZhang** [comment] 2020-11-02 13:32
Since we have rooted cause this issue in FFMpeg and @nyanmisaka provided FFMPEG patch for fix. Let's close this issue as fixed in FFMPEG. 

As for other issues, recommend to file issues on GitHub.

**Closed by FurongZhang** 2020-11-02 13:32 UTC
Labels: vpp

**Comment by FurongZhang** [comment] 2020-11-02 13:36
@nyanmisaka, FFMPEG should support VAAPI HDR tone mapping on KBL. And we are planning to add HDR tone mapping in MSDK level.
