### ISSUE TITLE
Sending frame into two packet to decode may cause GPU HANG on TGL and ICL, but works fine on SKL.

### ISSUE THREAD

**Issue by wenbinc-Bin** [Intel-Media-SDK/MediaSDK#2618] opened 2021-03-11 02:55 UTC
When I use MSDK api to decode video, one video return GPU HANG error. I traced the error and found there is a frame that have a special NAL order causes this problem. I copy the frame information from VQAnalyzer and listed below.

```
823239	3226: 39: PREFIX_SEI - Supplemental enhancement information, prefix: Picture timing (1)	0	0	15
823253	3227: 1: TRAIL_R - Coded slice segment of a non-TSA, non-STSA trailing picture, VPS:(13) SPS:(13) PPS:(42)	0	0	415
823669	3228: 33: SPS - Sequence parameter set, ID: (13)	0	0	345
824013	3229: 1: TRAIL_R - Coded slice segment of a non-TSA, non-STSA trailing picture, VPS:(13) SPS:(13) PPS:(42)	0	0	1039
825052	3230: 1: TRAIL_R - Coded slice segment of a non-TSA, non-STSA trailing picture, VPS:(13) SPS:(13) PPS:(42)	0	0	2419
827471	3231: 40: SUFFIX_SEI - Supplemental enhancement information, suffix: Decoded Picture Hash (132)	0	0	57

```
There is SPS between slice rather than in the head of unit.
If I use ffmpeg to parse the bitstream, ffmpeg will split this frame into two packets, the first two NAL and the last four NAL, and send two packets to MSDK to decode. I checked the LIBVA_TRACE log. It render picture twice to send all three slice, and then it report GPU hang error.
This error can be produced on TGL and ICL, but on SKL it works fine.

Sample_decode can successfully decode this video. I see sample_decode will read all the bitstream and pass it to MSDK together. MSDK will read tone frame until the first slice for the next frame. This is different from ffmpeg. I checked the LIBVA_TRACE log and it will render once to send all three slice.

**Comment by wenbinc-Bin** [comment] 2021-03-11 03:09
post LIBVA_TRACE log for two parse way.

ffmpeg's way to parse bitstream and send packets to MSDK:
```
[50879.579471][ctx 0x10000000]==========va_TraceBeginPicture
[50879.579471][ctx 0x10000000]	context = 0x10000000
[50879.579472][ctx 0x10000000]	render_targets = 0x00000003
[50879.579472][ctx 0x10000000]	frame_count  = #180
[50879.579481][ctx       none]=========vaBeginPicture ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579483][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579483][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579487][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579487][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579490][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579491][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579493][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579493][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579498][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579498][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579499][ctx       none]=========vaUnmapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579500][ctx 0x10000000]==========va_TraceRenderPicture
[50879.579500][ctx 0x10000000]	context = 0x10000000
[50879.579500][ctx 0x10000000]	num_buffers = 1
[50879.579500][ctx       none]=========vaBufferInfo ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579501][ctx 0x10000000]	---------------------------
[50879.579501][ctx 0x10000000]	buffers[0] = 0x00000000
[50879.579501][ctx 0x10000000]	  type = VAPictureParameterBufferType
[50879.579502][ctx 0x10000000]	  size = 604
[50879.579502][ctx 0x10000000]	  num_elements = 1
[50879.579502][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.579503][ctx 0x10000000]	element[0] = VAPictureParameterBufferHEVC
[50879.579503][ctx 0x10000000]	CurrPic.picture_id = 0x00000003
[50879.579503][ctx 0x10000000]	CurrPic.frame_idx = 133
[50879.579504][ctx 0x10000000]	CurrPic.flags = 0
.
.
.
[50879.579619][ctx 0x10000000]	---------------------------
[50879.579619][ctx 0x10000000]	buffers[0] = 0x00000002
[50879.579620][ctx 0x10000000]	  type = VASliceParameterBufferType
[50879.579620][ctx 0x10000000]	  size = 264
[50879.579620][ctx 0x10000000]	  num_elements = 1
.
.
.
[50879.580552][ctx 0x10000000]==========va_TraceBeginPicture
[50879.580553][ctx 0x10000000]	context = 0x10000000
[50879.580553][ctx 0x10000000]	render_targets = 0x00000000
[50879.580553][ctx 0x10000000]	frame_count  = #181
[50879.580569][ctx       none]=========vaBeginPicture ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580571][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580571][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580575][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580576][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580580][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580580][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580582][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580583][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580588][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580588][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580589][ctx       none]=========vaUnmapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580589][ctx 0x10000000]==========va_TraceRenderPicture
[50879.580590][ctx 0x10000000]	context = 0x10000000
[50879.580590][ctx 0x10000000]	num_buffers = 1
[50879.580590][ctx       none]=========vaBufferInfo ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580590][ctx 0x10000000]	---------------------------
[50879.580591][ctx 0x10000000]	buffers[0] = 0x00000004
[50879.580591][ctx 0x10000000]	  type = VAPictureParameterBufferType
[50879.580591][ctx 0x10000000]	  size = 604
[50879.580592][ctx 0x10000000]	  num_elements = 1
[50879.580592][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580592][ctx 0x10000000]	element[0] = VAPictureParameterBufferHEVC
[50879.580593][ctx 0x10000000]	CurrPic.picture_id = 0x00000000
[50879.580593][ctx 0x10000000]	CurrPic.frame_idx = 133
[50879.580594][ctx 0x10000000]	CurrPic.flags = 0
.
.
.
[50879.580725][ctx       none]=========vaBufferInfo ret = VA_STATUS_SUCCESS, success (no error) 
[50879.580726][ctx 0x10000000]	---------------------------
[50879.580726][ctx 0x10000000]	buffers[0] = 0x00000002
[50879.580726][ctx 0x10000000]	  type = VASliceParameterBufferType
[50879.580726][ctx 0x10000000]	  size = 264
[50879.580727][ctx 0x10000000]	  num_elements = 2
.
.
.
[50879.581029][ctx 0x10000000]==========va_TraceEndPicture

```

sample_decode's way to split packet and send to MSDK:
```
[31459.541321][ctx 0x10000000]==========va_TraceBeginPicture
[31459.541322][ctx 0x10000000]	context = 0x10000000
[31459.541322][ctx 0x10000000]	render_targets = 0x0000000a
[31459.541323][ctx 0x10000000]	frame_count  = #180
[31459.541331][ctx       none]=========vaBeginPicture ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541332][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541333][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541335][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541335][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541336][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541337][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541338][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541339][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541341][ctx       none]=========vaCreateBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541342][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541342][ctx       none]=========vaUnmapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541342][ctx 0x10000000]==========va_TraceRenderPicture
[31459.541343][ctx 0x10000000]	context = 0x10000000
[31459.541343][ctx 0x10000000]	num_buffers = 1
[31459.541343][ctx       none]=========vaBufferInfo ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541344][ctx 0x10000000]	---------------------------
[31459.541344][ctx 0x10000000]	buffers[0] = 0x00000003
[31459.541344][ctx 0x10000000]	  type = VAPictureParameterBufferType
[31459.541344][ctx 0x10000000]	  size = 604
[31459.541345][ctx 0x10000000]	  num_elements = 1
[31459.541345][ctx       none]=========vaMapBuffer ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541345][ctx 0x10000000]	element[0] = VAPictureParameterBufferHEVC
[31459.541346][ctx 0x10000000]	CurrPic.picture_id = 0x0000000a
[31459.541346][ctx 0x10000000]	CurrPic.frame_idx = 133
[31459.541346][ctx 0x10000000]	CurrPic.flags = 0
.
.
.
[31459.541467][ctx       none]=========vaBufferInfo ret = VA_STATUS_SUCCESS, success (no error) 
[31459.541467][ctx 0x10000000]	---------------------------
[31459.541467][ctx 0x10000000]	buffers[0] = 0x00000000
[31459.541467][ctx 0x10000000]	  type = VASliceParameterBufferType
[31459.541468][ctx 0x10000000]	  size = 264
[31459.541468][ctx 0x10000000]	  num_elements = 3
.
.
. 
[31459.541928][ctx 0x10000000]==========va_TraceEndPicture
```

**Comment by dmitryermilov** [comment] 2021-03-15 08:49
Hi @wenbinc-Bin ,

So you're saying that in fmpeg-qsv case, msdk decoder sends to UMD the sequence of NALU's, which you posted, as two frames? And it causes a GPU hang?
And in cases of sample_decode, it sends these 3 slices as one frames?

You know, I recall that that at least for AVC, the spec say that SPS can't occur between slices of one frame. Most likely there's the same in HEVC (need to check the spec). If so, msdk decoder the behavior with ffmpeg is the right now.

**Comment by wenbinc-Bin** [comment] 2021-03-15 09:52
Hi @dmitryermilov 

Ah! I disabled the MFX_BITSTREAM_COMPLETE_FRAME flag, and it works. Thanks. 
Because it can work on SKL but fail on TGL/ICL, I thought it is driver's problem.

FFmpeg-vaapi doesn't have this problem. FFmpeg-vaapi use ffmpeg's native parser to parse bitstream, and it drops all the illegal data, so ffmpeg-vaapi will lose the frames which can be decoded by sample_decode and VQAnalyzer. 

Thanks

**Comment by dmitryermilov** [comment] 2021-03-15 10:13
@wenbinc-Bin ,

> Because it can work on SKL but fail on TGL/ICL, I thought it is driver's problem.

Yes...

> FFmpeg-vaapi doesn't have this problem. FFmpeg-vaapi use ffmpeg's native parser to parse bitstream, and it drops all the illegal data

Msdk decoders usually do the same. If there're an opportunity to improve this, we need to do it :)

**Comment by dmitryermilov** [comment] 2021-03-15 20:23
@wenbinc-Bin , 

> You know, I recall that that at least for AVC, the spec say that SPS can't occur between slices of one frame. Most likely there's the same in HEVC (need to check the spec). If so, msdk decoder the behavior with ffmpeg is the right now, even thought it causes a GPU hang.

I was wrong. We did this change for HEVC. Here it is https://github.com/intel-innersource/drivers.gpu.media.sdk.lib/commit/d5c8e053427b9ecf1091d22f3a8355a745008529 . Now it looks weird that with sample_decode it doesn't behave this way. 
@wenbinc-Bin , if you have bandwidth, could you debug the case and check if "m_Headers.m_SeqParams.GetCurrentHeader()->m_changed" becomes true with the stream?

**Comment by wenbinc-Bin** [comment] 2021-03-16 02:48
Hi @dmitryermilov. I debug the case and the m_changed is false when decode the first slice after SPS.

**Comment by dmitryermilov** [comment] 2021-03-16 07:00
Interesting.. Please look at comment in the commit I posted above:
_// Accord. to ITU-T H.265 7.4.2.4 Any SPS/PPS w/ id equal to active one
// shall have the same content, unless it follows the last VCL NAL of the coded picture
// and precedes the first VCL NAL unit of another coded picture_

So I suspect that this SPS (where  GPU hang occurs) is equal to previous one. If so, the ffmpeg bitstream parser logic shouldn't complete current frame.

**Comment by wenbinc-Bin** [comment] 2021-03-16 08:02
Yes, I checked and this SPS is equal to the previous one.

FFmpeg's parser only extract video parameter and won't split bitstream. FFmpeg split bitstream into packets only according to what type of the NAL. It seems that the flag MFX_BITSTREAM_COMPLETE_FRAME should not be set for ffmpeg-qsv.

**Comment by dmitryermilov** [comment] 2021-03-16 08:34
> FFmpeg's parser only extract video parameter and won't split bitstream. FFmpeg split bitstream into packets only according to what type of the NAL. It seems that the flag MFX_BITSTREAM_COMPLETE_FRAME should not be set for ffmpeg-qsv.

If ffmpeg parser doesn't really attempt to construct a frame (btw, @xhaihao , could you confirm?), then yes, MFX_BITSTREAM_COMPLETE_FRAME should not be set.

**Comment by xhaihao** [comment] 2021-03-17 00:38
The flag MFX_BITSTREAM_COMPLETE_FRAME needs a complete frame or complementary field pair of data, so we shouldn't set this flag for this case. On the other hand, MFX_BITSTREAM_COMPLETE_FRAME impacts the decoding latency but Media SDK can work well without this flag for a complete frame or complementary field pair. In the past, we set this flag  in gst-msdk and removed it to workaround some issues. Currently MFX_BITSTREAM_COMPLETE_FRAME is set only for DecodedOrder = 1.

**Comment by wenbinc-Bin** [comment] 2021-03-17 02:04
@xhaihao Ok, I will submit a patch to remove this flag in ffmpeg-qsv.

**Comment by uartie** [comment] 2021-03-18 06:58
@wenbinc-Bin can you provide a link (in this issue) to your ffmpeg-qsv patch so others can trace it easily?

**Comment by wenbinc-Bin** [comment] 2021-03-18 07:08
@uartie ok, later after I submit the patch to the community I will post a link here. I need to submit it to ci to test it.

**Comment by wenbinc-Bin** [comment] 2021-03-19 05:28
@dmitryermilov Hi, after I removed the flag, there are new error on vc1 decoder. It report a segmentation fault. The fault occurs here https://github.com/Intel-Media-SDK/MediaSDK/blob/76ceda51acd1dfa041e472cc0ee409e9a71931d3/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp#L1134

stCodes->count equals to 0.

**Comment by dmitryermilov** [comment] 2021-03-19 09:17
@wangyan-intel , can you please investigate? 
@wenbinc-Bin , please share ffmpeg build, stream and command line

**Comment by wangyan-intel** [comment] 2021-03-19 09:21
@dmitryermilov Sure. I will take a look.

**Comment by wenbinc-Bin** [comment] 2021-03-19 09:46
@wangyan-intel Hi I removed the flag MFX_BITSTREAM_COMPLETE_FRAME and VC1 reports segmentation fault. Here is my patch https://github.com/wenbinc-Bin/ffmpeg-ci/commit/46595339712e94fb251102cbc06e7e032a1123b5
cmdline: ffmpeg -c:v vc1_qsv -i input.vc1 -y output.yuv
I will send stream to you by intel-email.

**Comment by wenbinc-Bin** [comment] 2021-03-22 05:36
I may not describe the question well and I add more detail here. The new error only occur on ffmpeg-qsv after remote the COMPLETE_FRAME flag. It seems that if I pass a segment of VC1 bitsteam without COMPLETE_FRAME flag and without startcode, MSDK will report segment fault. According to the error code, I think the problem is about the code's robustness. I tried to fix the issue and post the patch below. (This patch is only to show my idea but isn't a strict fix patch.)

```
From b309e96e866d5b2527c2d9205a38ca5bbeba9c6b Mon Sep 17 00:00:00 2001
From: "Chen,Wenbin" <wenbin.chen@intel.com>
Date: Mon, 22 Mar 2021 13:25:28 +0800
Subject: [PATCH] try to fix

---
 .../shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp    | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp b/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
index f54f3e64..40565101 100644
--- a/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
+++ b/_studio/shared/umc/codec/vc1_dec/src/umc_vc1_video_decoder.cpp
@@ -1131,6 +1131,10 @@ Status VC1VideoDecoder::GetStartCodes (uint8_t* pDataPointer,
         else
         {
             // last portion pf user data
+            if (stCodes->count == 0)
+            {
+                return UMC_ERR_NOT_ENOUGH_DATA;
+            }
             if (!IS_VC1_USER_DATA(stCodes->values[stCodes->count - 1] >> 24) || isWriteSlice)
             {
                 //end of stream
-- 
2.25.1
```

**Comment by wangyan-intel** [comment] 2021-06-16 02:52
@pengxin99 Could you please take a look?

**Comment by wenbinc-Bin** [comment] 2021-07-08 06:15
Any progress on this issue?

**Comment by pengxin99** [comment] 2021-08-09 09:22
@wenbinc-Bin , sorry for the later response, I have reproduced this and found: when `readBufSize == 1`, it means input mediaData is too small and will hit the below code, but this code is to deal with the last portion of user data,  not consider this small input mediaData situation. Still need to do further investigation.

**Comment by wangyan-intel** [comment] 2022-04-07 02:22
Close this issue because https://github.com/Intel-Media-SDK/MediaSDK/pull/2832 has been merged.

**Closed by wangyan-intel** 2022-04-07 02:22 UTC
Labels: decode
