### ISSUE TITLE
Wrong colors in RGB->NV12 conversion

### ISSUE THREAD

**Issue by HermanMolinder** [Intel-Media-SDK/MediaSDK#1857] opened 2019-12-19 09:38 UTC
I have only tested with VPP composite conversion from RGB to NV12 on an apollo lake processor, with following set up:
InputStream[0] is a black RGB frame with R=0, G=0, B=0 and covers complete frame.
InputStream[1] is an RGB frame and contains below color bars and covers complete frame.
Composite background color is set to black with Y=0x10, U=0x80, V=0x80.

The RGD codes for 75% intensity color bars has following values:
```
white:  R=0xff, G=0xff, B=0xff
yellow: R=0xbf, G=0xbf, B=0x00
cyan: R=0x00, G=0xbf, B=0xbf
green: R=0x00, G=0xbf, B=0x00
magenta: R=0xbf, G=0x00, B=0xbf
red: R=0xbf, G=0x00, B=0x00
blue: R=0x00, G=0x00, B=0xbf
black: R=0x00, G=0x00, B=0x00
```
The NV12 result from msdk:

```
white: Y=0xed, U=0x80, V=0x80
yellow: Y=0xa2, U=0x2c, V=0x8d
cyan: Y=0x84, U=0x9c, V=0x2c
green: Y=0x71, U=0x49, V=0x3a
magenta: Y=0x55, U=0xb7, V=0xc6
red: Y=0x41, U=0x64, V=0xd4
blue: Y=0x23, U=0xd4, V=0x73
black: Y=0x10, U=0x80, V=0x80
```

Expected NV12 result according to BT.601:

```
white: Y=0xeb, U=0x80, V=0x80
yellow: Y=0xa2, U=0x2c, V=0x8e
cyan: Y=0x83, U=0x9c, V=0x2c
green: Y=0x70, U=0x48, V=0x3a
magenta: Y=0x54, U=0xb8, V=0xc6
red: Y=0x41, U=0x64, V=0xd4
blue: Y=0x23, U=0xd4, V=0x72
black: Y=0x10, U=0x80, V=0x80
```

As you see the values are very close, and could be a rounding error? I just wanted to let you know since I did a quite thorough investigation of this.

**Comment by dmitryermilov** [comment] 2019-12-19 13:25
Hi Herman,

It's a know problem. To address it there is the chroma sitting feature. Please refer to [mfxExtColorConversion](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxextcolorconversion) , [ChromaSiting](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#chromasiting)

**Comment by HermanMolinder** [comment] 2019-12-19 13:44
Hi Dmitry,

Thank you! I will experiment with those parameters.

**Comment by HermanMolinder** [comment] 2019-12-19 14:14
I get the same result when trying top and center siting. As I understand siting is used in the downsampling process. In my case all 4.4.4 pixels have the same RGB value, so siting algorithm shouldn't affect the result in my case.

**Comment by dmitryermilov** [comment] 2019-12-19 14:50
Chroma siting describes how chroma values are positioned relative to the luma samples.

- Option A: MFX_CHROMA_SITING_VERTICAL_TOP | MFX_CHROMA_SITING_HORIZONTAL_LEFT 
- Option B: MFX_CHROMA_SITING_VERTICAL_BOTTOM | MFX_CHROMA_SITING_HORIZONTAL_LEFT 
- Option AC: MFX_CHROMA_SITING_VERTICAL_TOP | MFX_CHROMA_SITING_HORIZONTAL_CENTER
- Option BD: MFX_CHROMA_SITING_VERTICAL_BOTTOM | MFX_CHROMA_SITING_HORIZONTAL_CENTER
- Option AB: MFX_CHROMA_SITING_VERTICAL_CENTER | MFX_CHROMA_SITING_HORIZONTAL_LEFT
- Option ABCD: MFX_CHROMA_SITING_VERTICAL_CENTER | MFX_CHROMA_SITING_HORIZONTAL_CENTER

Which code base do you use? Please note the chroma sitting had a bug and got a fix just 3 days ago: https://github.com/Intel-Media-SDK/MediaSDK/pull/1837/files

BTW, you can check via sample_vpp, e.g.:
`./sample_vpp -sw 960 -sh 540 -scc rgb4 -dw 960 -dh 540 -dcc nv12 -chroma_siting vcen hcen -i test.rgb -o out.nv12`

**Comment by HermanMolinder** [comment] 2019-12-20 07:43
I see! We use a much older revision than that. 
As this is not a big issue for us I can't prioritize this right now, unfortunately. I hope I have time testing this next year though. 

Merry Christmas and Happy New Year Dmitry!

**Comment by dmitryermilov** [comment] 2019-12-31 13:31
Thank you. Happy New Year, Herman :)

**Comment by dmitryermilov** [comment] 2020-01-17 23:23
Hi Herman,

Did you have a chance to come back to it?

**Comment by HermanMolinder** [comment] 2020-01-20 07:12
Hi Dmitry,
No, unfortunately not. We plan to update our msdk version later this spring, so I will test it then.

**Comment by HermanMolinder** [comment] 2020-09-02 10:11
@dmitryermilov ,

I've tested chroma siting (top|left) now with fix: https://github.com/Intel-Media-SDK/MediaSDK/pull/1837/files

I still get the same behavior as before. However this is not a problem for me, so no need to prioritize this issue for my sake. I just wanted to give you the feedback.

**Comment by dmitryermilov** [comment] 2020-09-11 15:28
Thank you @HermanMolinder for the update. @FurongZhang , did you have a chance to look into the issue?
BTW, Herman, I'll be unavailable next two weeks. Just in case.

**Comment by daleksan** [comment] 2020-10-15 10:41
@FurongZhang can you please reply?

**Comment by FurongZhang** [comment] 2020-10-15 14:07
Yeah, I can reply. I looked at this issue. The bit difference is 1(very small). 

For our fixed function(HW unit), we don't expect this difference. On our latest platform ICL/TGL, we once confirmed that this CSC is same as the mathematics calculation. 

If CSC is running on EU, it is possible because of some rounding precision issue.

**Comment by FurongZhang** [comment] 2020-10-15 14:09
@HermanMolinder, what is your expectation of this issue? 

For APL, we have limited support. I can double confirm ICL and TGL. Is this OK for you? 

Or you expect us to fix this issue on APL?

Thanks,
Furong

**Comment by HermanMolinder** [comment] 2020-10-15 14:28
@FurongZhang ,
This issue is not affecting me. As you say the difference is very small, so I'm not expecting a fix for APL.
The other two opened issues I've created is of higher priority though. They are actual bugs in our product.

BR
Herman

**Comment by FurongZhang** [comment] 2020-10-15 14:32
OK. I am checking the issue you reported.

**Comment by FurongZhang** [comment] 2020-10-15 14:32
Can you please pasted the bug again?

**Comment by FurongZhang** [comment] 2020-10-15 14:38
Recently, I am cleaning MSDK issues. If this is not affecting you, I will close the issue. Please feel free to let me know if any concern.

**Closed by FurongZhang** 2020-10-15 14:38 UTC
Labels: vpp

**Comment by samuel100u** [comment] 2021-06-09 02:13
> Hi Herman,
> 
> It's a know problem. To address it there is the chroma sitting feature. Please refer to [mfxExtColorConversion](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#mfxextcolorconversion) , [ChromaSiting](https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#chromasiting)

Hi @dmitryermilov 

I noticed that RGB4 ([0,255])  to NV12 will produce YUV [16,235].

Is there way to specify full color range when convert to NV12?

Thank you.

**Comment by brmarkus** [comment] 2021-06-09 05:33
Full-Color-Range - please have a look into e.g. sample_decode, which supports a command-line-parameter "-rgb4_fcr", which finally is applying:
```
        m_VppVideoSignalInfo.TransferMatrix = MFX_TRANSFERMATRIX_UNKNOWN;
        m_VppVideoSignalInfo.NominalRange = MFX_NOMINALRANGE_0_255;
```
