### ISSUE TITLE
MFXVideoENCODE_Reset is not supported for LookAhead (except MaxSliceSize change)

### ISSUE THREAD

**Issue by YaboWei** [Intel-Media-SDK/MediaSDK#487] opened 2018-08-07 03:15 UTC
Hi, 

I want encoded gop struct follow input, but MFXVideoENCODE_Reset failed if lookahead enabled.

see also:
https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/issues/36

thanks

**Comment by dvrogozh** [comment] 2018-08-21 20:54
As of https://github.com/Intel-Media-SDK/MediaSDK/commit/93f559e9c527f6542829bde5602c89394b0ce85a can be reproduced with the command line:

```
ffmpeg \
  -hwaccel qsv -c:v h264_qsv -i file.264 \
  -force_key_frames source -c:v h264_qsv -b:v 2000k -preset medium -bf 1 -g 1000 -force_idr 1 \
  -look_ahead 1 -look_ahead_depth 20 -an -f flv -y qsv_idr.flv -loglevel verbose
```

Error (-14) comes from AVC encoder implementation of MFXVideoENCODE_Reset uAPI call. Stepping into the code we have this exact place of the error:
https://github.com/Intel-Media-SDK/MediaSDK/blob/93f559e9c527f6542829bde5602c89394b0ce85a/_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp#L1249

The full check which failed looks as follows:
```
    MFX_CHECK(!((m_video.mfx.RateControlMethod == MFX_RATECONTROL_LA ||
                m_video.mfx.RateControlMethod == MFX_RATECONTROL_LA_EXT ||
                m_video.mfx.RateControlMethod == MFX_RATECONTROL_LA_HRD) &&
                !IsOn(m_video.mfx.LowPower) && extOpt2New->MaxSliceSize == 0),
              MFX_ERR_INCOMPATIBLE_VIDEO_PARAM);
```

If I read it correctly, it means that if encoder works with the above 3 LA modes then _any_ encode Reset will fail unless user adjusts MaxSliceSize to non-zero value. In my mind this check does not make sense.

**Comment by dvrogozh** [comment] 2018-08-22 17:40
I clarified the status of Reset support for LA. Indeed, as the check mentioned above suggests, right now MFXVideoENCODE_Reset for LA is not supported except a single exception of changing MaxSliceSize. We are clarifying now whether we can support the reset fully. I will update the outcome later on.

However, in the particular usage case reported in the Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins#36, i.e. force IDR frames, we believe that you should not use Reset at all since it will give runtime overhead. Instead, you can try to use mfxEncodeCtrl::FrameType uAPI and pass it to EncodeFrameAsync call:
https://github.com/Intel-Media-SDK/MediaSDK/blob/904956c46f98b70dab8fa01380e71c06f8da7cb8/api/include/mfxstructures.h#L1002. Here are guidelines to properly use this API:
* Program FrameType as: 
`ctrl.FrameType = MFX_FRAMETYPE_I | MFX_FRAMETYPE_IDR | MFX_FRAMETYPE_REF;`
* Make sure that the following is true for mfxEncodeCtrl object:
** mfxEncodeCtrl lifetime ends _after_ successfull return from the corresponding SyncOperation
** You don't reuse mfxEncodeCtrl for any other frame if you already passed it to EncodeFrameAsync and SyncOperation is not completed.

**Comment by dvrogozh** [comment] 2018-08-22 17:49
This issue is a feature request to support Reset for LA. Labeling it accordingly... Please, file separate issue in case of any issues with mfxEncodeCtrl::FrameType uAPI on LA.

**Comment by YaboWei** [comment] 2018-08-29 09:44
@dvrogozh 
force idr works well if I only ctrl.FrameType and no Reset(), thanks a lot.

**Comment by vvkalinin24** [comment] 2019-10-16 13:36
@YaboWei Could we close this issues?

**Comment by daleksan** [comment] 2020-08-06 10:47
feel free to re-open if issue still actual

**Closed by daleksan** 2020-08-06 10:47 UTC
Labels: feature request
