### ISSUE TITLE
New 19.4 MSDK env: Running sample_decode will cause "segmentation fault (core dumped)" by adding "-r" option in X mode. 

### ISSUE THREAD

**Issue by bbao3** [Intel-Media-SDK/MediaSDK#1916] opened 2020-01-17 07:51 UTC
Hi, I installed the latest 19.4 MSDK and media-driver with all the required dependencies. But there is a new "segmentation fault (core dumped)" issue in this new release package. Reuse sample_decode of 19.3.1 can replicate the same issue, so suspect this issue is related with rendering. But since it belongs to MSDK package, can you help to find the root cause?

The command and log output like below:
root@intel-dbg:/opt/intel/mediasdk/share/mfx/samples# ./sample_decode h264 -i /video.h264 -hw -vaapi -rgb4 -r
libva info: VA-API version 1.6.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/local/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
Decoding Sample Version 19.4.0

Input video	AVC 
Output format	RGB4 (using vpp)
Input:
  Resolution	1920x1088
  Crop X,Y,W,H	0,0,1920,1080
Output:
  Resolution	1920x1080
Frame rate	50.00
Memory type		vaapi
MediaSDK impl		hw
MediaSDK version	1.31

Decoding started
**Segmentation fault (core dumped)fread_fps: 0.000, fwrite_fps: 0.000**
root@intel-dbg:/opt/intel/mediasdk/share/mfx/samples# 

Regards,
Bruce

**Comment by dmitryermilov** [comment] 2020-01-17 09:05
@AntonGrishin , please prioritize

**Comment by AntonGrishin** [comment] 2020-01-20 11:28
Hi @bbao3,

Seems it`s regression in LibVA (since https://github.com/intel/libva/pull/351 merged). On latest libva master all works, but on tag/2.6.0 (which provided in release)  sample crashes.

**Comment by bbao3** [comment] 2020-01-22 02:02
Thank you AntonGrishin, so will we release another MSDK (e.g. 19.4.1) later to make sure end-user will not be confused with this LibVA issue?

**Comment by AntonGrishin** [comment] 2020-01-30 09:10
@onabiull can you comment on this?

**Closed** 2020-08-20 11:01 UTC
