### ISSUE TITLE
"Failed to define max_display_attributes" error with FFmpeg

### ISSUE THREAD

**Issue by ViGill** [Intel-Media-SDK/MediaSDK#114] opened 2018-03-26 14:30 UTC
Hi,

I use the latest gits and libva with the recommended tag.
I followed the full compiling procedure and I end up with the following error in ffmpeg:

[AVHWDeviceContext @ 0x22b8860] Cannot open X11 display .
[AVHWDeviceContext @ 0x22b8860] Opened VA display via DRM device /dev/dri/renderD128.
[AVHWDeviceContext @ 0x22b8860] libva: VA-API version 1.0.0
[AVHWDeviceContext @ 0x22b8860] libva: va_getDriverName() returns 0
[AVHWDeviceContext @ 0x22b8860] libva: User requested driver 'iHD'
[AVHWDeviceContext @ 0x22b8860] libva: Trying to open /usr/local/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x22b8860] libva: Found init function __vaDriverInit_1_0
[AVHWDeviceContext @ 0x22b8860] libva: Failed to define max_display_attributes in init
[AVHWDeviceContext @ 0x22b8860] libva: /usr/local/lib/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x22b8860] libva: va_openDriver() returns -1
[AVHWDeviceContext @ 0x22b8860] Failed to initialise VAAPI connection: -1 (unknown libva error).

Is it a known issue ?

Thanks

**Comment by maxha651** [comment] 2018-04-10 11:36
Hi,

I'm getting the same error but for another setup.

https://github.com/intel/media-driver seems to want libva master instead, so it might be worth trying with that.

What is the rationale behind the "special version" of libva?

**Comment by maxha651** [comment] 2018-04-11 07:41
I tried with libva master and the error went away. Is the very important special libva version from the README really that important/special?

**Comment by onabiull** [comment] 2018-04-11 11:29
Sorry, readme.md outdated in this regard. This was true at the time of posting. I'll correct it.

**Comment by maxha651** [comment] 2018-04-11 11:46
Thanks!

**Comment by maxha651** [comment] 2018-05-07 09:16
I think this issue can be closed...

Unless @ViGill has anything against it?

**Comment by adydychk** [comment] 2018-05-23 07:39
@ViGill can we close this issue?

**Comment by adydychk** [comment] 2018-06-05 09:44
It seems like the problem is solved if you will have another feel free to open one more issue ;)

**Closed by adydychk** 2018-06-05 09:44 UTC
Labels: question
