### ISSUE TITLE
Encode h.265: Multiple sessions in a serie

### ISSUE THREAD

**Issue by CFahrniBY** [Intel-Media-SDK/MediaSDK#2864] opened 2021-12-22 18:09 UTC
In a .cpp project I wrote a class based on `simple_encode_hevc10.cpp` to encode images to a video stream. 
In the first movie all frames are written as expected to the video stream.
Once the HW is initialized the system should write other videos in a sequence.
For doing that I use `mfxENC` again. But this fails with errors from the Hardware.
For me it is important to initialize the GPU (Kaby Lake) only once because of the 1s it uses to initialize.

My application is implemented this way:
- init(): - to initialize the HW
- start(fileName): - to start a new stream
- writeImg(img): - to encode new frames
- stop(): - to flush buffers and cleanup

The sequence would be: init, start, writeImg (100x), stop, start, writeImg (100x), stop, start, writeImg (100x), stop, ...

## System information
- CPU i7, Debian x64
- GPU Kaby Lake `/dev/dri/render128`

### Describe the current behavior
 - Using existing handler `mfxENC` for the next move ends with errors from HW.
 - Allocating another `mfxENC` not work neither.

### Describe the expected behavior
 - After cleaning up the session correctly whith `mfxENC.Close()` it should be possible to reuse the interface. 

I report this to be a bug because the system should be able to write several videos after initialization. But it can also seen as a new feature.

I would be very glad to get some support from the experts. Best regards, Chris

**Comment by dmitryermilov** [comment] 2021-12-22 22:08
It would be great to see source code or at least have API traces (https://github.com/Intel-Media-SDK/MediaSDK/tree/master/tools/tracer). 
But generally I guess the issue is when you create the other mfxENC you need the other mfxSession at first. One session can have one decoder, one VPP and one encoder.

**Comment by CFahrniBY** [comment] 2021-12-23 08:16
Thank you. Please find attached the trace log and class I wrote. In the `stop()` routine the cleanup is inactive because the handler will be used for the next file initialized with `start()`.
[traceAndSrc.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/7767718/traceAndSrc.zip)
## Issue behavior
 - At the 2nd call of `sts = m_mfxENC->Init(&m_mfxEncParams);` the method returns `MFX_ERR_UNDEFINED_BEHAVIOR`.

**Comment by dmitryermilov** [comment] 2021-12-26 22:06
I looked at the code and logs.

1. It seems logs don't match to the cpp file. It's because I code I don't see Encode::Close but it's present in logs.
2. In logs Close returned MFX_ERR_DEVICE_FAILED but you're writing about MFX_ERR_UNDEFINED_BEHAVIOR
3. Leaving aside above, no clue of the issue looking at logs. You're doing 2nd Init with exactly same params at in 1st run.

Could you add `#define MFX_DEBUG_TRACE` at line https://github.com/Intel-Media-SDK/MediaSDK/blob/0db73aa1b2dec5b61900ee54db3fa574de6d1752/_studio/shared/include/mfx_utils_defs.h#L28  
rebuild mskd library and re-run the use case? With such define you'll get logs where an error was generated in msdk soure code. Let's take a  look.

**Comment by CFahrniBY** [comment] 2022-01-06 09:19
I went trough your points:

1. The Method `MFXClose` is called in the destructor of the class `MFXVideoSession`.
2. The 2nd call of `m_mfxENC->Init()` returns `MFX_ERR_UNDEFINED_BEHAVIOR`.
3. Yes, you are right, I use the same parameters. I assume that `Init()` is required to initialize a new video file. I run a test that calls `Init()` only once. See _Behavior with single Init()_

## New trace with code from 23.12.21
I added the `MFX_DEBUG_TRACE` and got the following output:

```
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/local/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_6
libva info: va_openDriver() returns 0
 Undefined behavior. ../imageProcessor/videoio/videoEncoderHvec10.cpp 265
../imageProcessor/test/videoWriter_test.cpp:95: Failure
```
[mfxtracer_32274.log](https://github.com/Intel-Media-SDK/MediaSDK/files/7820405/mfxtracer_32274.log)

## Behavior with single Init()
[singleInit.zip](https://github.com/Intel-Media-SDK/MediaSDK/files/7820562/singleInit.zip)
1. I don't get any error
2. The 2nd video file is smaller and cannot be extracted by ffmpeg. Maybe the header is missing...

- I wondered what steps are required to start another video file.
- I wondered if should be used for every file CloneSession() - but the method does not handle a MFXVideoSession

**Comment by dmitryermilov** [comment] 2022-01-10 15:36
> The Method MFXClose is called in the destructor of the class MFXVideoSession.

I meant MFXVideoENCODE::Close(). I don't see you call it (at least looking at videoEncoderHvec10.cpp you shared before). **It confuses me and makes me think you shared not exactly the same cpp/h file on which you experiment.** 

> The 2nd call of m_mfxENC->Init() returns MFX_ERR_UNDEFINED_BEHAVIOR

Yes, now in log file mfxtracer_32274.log it's present. But in this log file there's no MFXVideoENCODE::Close call :) . Now it matches the code but seems the app has an issue: Instead of making Init/Close/Encode../Init/Close, app is doing  Init/Encode../Init

> I added the MFX_DEBUG_TRACE and got the following output:

Thanks. But my point was you would rebuild libmfxhw64.so.1.35 and replace it on the system. Lack of console logs means you probably didn't replace the library.

> The 2nd video file is smaller and cannot be extracted by ffmpeg. Maybe the header is missing...

Yes, no headers. It's because a valid stream shall start from IDR frame and has SPS/PPS in front of it. It's called Random Access Point.

To avoid confusion I mentioned above it would be great if you can share code which I can successfully compile and run on my side. If possible please upload to some sandbox github project. In this case, it would be simpler to point to exact lines of code which confuses me.

If you can't share it's also okay. In this case please just make sure your app is doing these sequence:

1. create vaDisplay
2. Create MFXVideoSession
3.  Call SetHandle(session, vaDisplay)
4. Allocate surfaces
5. Create MFXVideoENCODE object
6. Init MFXVideoENCODE object
7. Encode several frames
8. When doing stop, drain encoder by calling EncodeFrameAsync with nullptr
9. Close MFXVideoENCODE object, 
10. Repeat 6-9
...
11. Destroy MFXVideoENCODE, MFXVideoSession objects and surfaces.

**Comment by dmitryermilov** [comment] 2022-01-12 22:22
Discussed offline. Fixed on app side.

**Closed by dmitryermilov** 2022-01-12 22:22 UTC
Labels: question
