### ISSUE TITLE
GPU hang found when did avc and hevc 8bit encode by using sample_encode on EHL platform

### ISSUE THREAD

**Issue by dryjq** [Intel-Media-SDK/MediaSDK#2032] opened 2020-03-23 07:04 UTC
GPU hang occurs when sample encode processes AVC and hevc 8bit streams, and there are many cases of failure. After analysis, it may be the cause of parameter “-u veryslow” and "-u slow",while  parameters "-u medium", "-u fast", "-u faster", "-u veryfaster" and so on will not cause this problem.
CMD:
sample_encode h264  -i /home/media_asset_nfs/yuv/stockholm_1280x720 _604_1280x720_I420.yuv -o /home/lbuild/1.h264 -w 1280 -h 720 -b 1000 -f 50 -u veryslow -num_slice 1 -idr_interval 1 -CodecProfile 77 -r 3 -g 30 -vbr
ERROR: 
[ERROR], sts=MFX_ERR_GPU_HANG(-21), SynchronizeFirstTask, SyncOperation failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:153
[ERROR], sts=MFX_ERR_GPU_HANG(-21), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2030
[ERROR], sts=MFX_ERR_GPU_HANG(-21), Run, m_pmfxENC->EncodeFrameAsync failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2256
[ERROR], sts=MFX_ERR_GPU_HANG(-21), main, pPipeline->Run failed at /home/build/MediaSDK/samples/sample_encode/src/sample_encode.cpp:1655
Frame number: 1
Encoding fps: 54
root@ssp-ehl-CDI376:/home/build# dmesg
[1142818.326122] i915 0000:00:02.0: Resetting rcs0 for preemption time out
[1142824.214121] i915 0000:00:02.0: Resetting rcs0 for preemption time out

**Comment by saosipov** [comment] 2020-03-24 07:04
Looks like timeout is exceeded. Could you increase it from cmd line?
Could you also share your cmd line for hevc encoding?

**Comment by dryjq** [comment] 2020-03-27 06:35
The cmd of hevc encoding is :
sample_encode -hw h265  -i /home/media_asset_nfs/yuv/stockholm_1280x720_604_1280x720.P010 -o 1.h265 -w 1280 -h 720 -b 1000 -f 50 -u veryslow -num_slice 1 -idr_interval 1  -r 3 -g 30 -x 3 -vbr -lowpower:on

Error:
[MOS]:  CRITICAL - SubmitCommandBuffer:1129: Command buffer submission failed!
[CODEC]:CRITICAL - SubmitCommandBuffer:5481: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteSliceLevel:2502: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteSliceLevel:2348: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteEnc:4491: Slice level encoding failed.
[CODEC]:CRITICAL - Execute:588: MOS returned error, eStatus = 0x22
[LIBVA]:CRITICAL - EncodeInCodecHal:392: DDI:Failed in Codechal!
[LIBVA]:CRITICAL - EndPicture:81: DDI:DdiEncode_EncodeInCodecHal return failure.

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), SynchronizeFirstTask, SyncOperation failed at /home/l/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:153

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2032

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), Run, m_pmfxENC->EncodeFrameAsync failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2258

ERROR: Hardware device was lost or returned an unexpected error. Recovering...

[ERROR], sts=MFX_ERR_ABORTED(-12), SynchronizeFirstTask, SyncOperation failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:153

[ERROR], sts=MFX_ERR_ABORTED(-12), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2032

**Comment by dryjq** [comment] 2020-03-27 06:37
The cmd of hevc encoding is :
sample_encode -hw h265  -i /home/media_asset_nfs/yuv/stockholm_1280x720_604_1280x720.P010 -o 1.h265 -w 1280 -h 720 -b 1000 -f 50 -u veryslow -num_slice 1 -idr_interval 1  -r 3 -g 30 -x 3 -vbr -lowpower:on

Error:
[MOS]:  CRITICAL - SubmitCommandBuffer:1129: Command buffer submission failed!
[CODEC]:CRITICAL - SubmitCommandBuffer:5481: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteSliceLevel:2502: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteSliceLevel:2348: MOS returned error, eStatus = 0x22
[CODEC]:CRITICAL - ExecuteEnc:4491: Slice level encoding failed.
[CODEC]:CRITICAL - Execute:588: MOS returned error, eStatus = 0x22
[LIBVA]:CRITICAL - EncodeInCodecHal:392: DDI:Failed in Codechal!
[LIBVA]:CRITICAL - EndPicture:81: DDI:DdiEncode_EncodeInCodecHal return failure.

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), SynchronizeFirstTask, SyncOperation failed at /home/l/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:153

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2032

[ERROR], sts=MFX_ERR_DEVICE_FAILED(-17), Run, m_pmfxENC->EncodeFrameAsync failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2258

ERROR: Hardware device was lost or returned an unexpected error. Recovering...

[ERROR], sts=MFX_ERR_ABORTED(-12), SynchronizeFirstTask, SyncOperation failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:153

[ERROR], sts=MFX_ERR_ABORTED(-12), GetFreeTask, m_TaskPool.SynchronizeFirstTask failed at /home/build/MediaSDK/samples/sample_encode/src/pipeline_encode.cpp:2032
root@ssp-ehl-CDI376:/home/build# dmesg
[88249.296663] i915 0000:00:02.0: Resetting rcs0 for preemption time out
[88255.184660] i915 0000:00:02.0: Resetting rcs0 for preemption time out
[88261.072660] i915 0000:00:02.0: Resetting rcs0 for preemption time out

**Comment by dryjq** [comment] 2020-04-29 07:00
It has been a long time since my bug was proposed. Has the bug been fixed now, or is it being fixed? Please reply, thank you

**Comment by DenWolf** [comment] 2020-05-20 08:47
Hi @dryjq ,

Regarding the information from you I suspect that current issue is not on Media SDK side, it's on Media Driver side (https://github.com/intel/media-driver).
I suppose that it's related to incorrect HME enabling on Target Usage 1 (== “-u veryslow” and "-u slow") both for AVC and HEVC VDEnc.

You can check it by "debug" disabling HME for Gen11 in driver:
I think you can just modify the function CodechalVdencAvcStateG11::ExecuteMeKernel - please try to disable the next if with HME (make the condition "false") - https://github.com/intel/media-driver/blob/master/media_driver/agnostic/gen11/codec/hal/codechal_vdenc_avc_g11.cpp#L1652

After that please rebuild the driver and run your experiments test again. If you will observe any issues - feel free to contact me here

Best regards,
Denis

**Comment by daleksan** [comment] 2020-10-15 10:53
@dryjq did you have a chance to try the Denis's suggestion?

**Comment by daleksan** [comment] 2021-06-09 22:30
Hi @dryjq is it still actual for you?

**Comment by DenWolf** [comment] 2021-06-16 14:42
Current issue has been resolved for a long time ago on a **Media Driver** side - https://github.com/intel/media-driver - close it as not actual.
@dryjq - if the issue is still reproducible on your side, please let me know and reopen this ticket.

Thank you,
Denis

**Closed by DenWolf** 2021-06-16 14:42 UTC
Labels: AVCe, HEVCe
